name: "ATLAS-D2K Center"

description: "The ATLAS-D2K is bringing data to knowledge for biomedical researchers in the kidney and lower urinary tract domains."

markdown: kramdown

permalink: pretty

paginate: 10
paginate_path: "news/page:num/"

port: 8000

plugins:
  - jekyll-paginate
