name: "ATLAS-D2K Center"

description: "The ATLAS-D2K is bringing data to knowledge for biomedical researchers in the kidney and lower urinary tract domains."

markdown: kramdown

permalink: pretty

sass:
    load_paths:
        - assets/css
        - rebuildingakidney/assets/css

paginate: 10
paginate_path: "news/page:num/"

scholar:
  bibliography: '**/*.bib'
  sort-by: year
  order: descending
  group_by: year
  group_order: descending
  bibliography_template: bib-entry
  bibliography_group_tag: 'h4,h5,h6'

page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: 'rebuildingakidney.projects'
    template: 'rbk_projects'
    name: 'tag'
    dir: 'rebuildingakidney/projects'


port: 8000

plugins:
  - jekyll-paginate
  - jekyll-scholar
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-datapage-generator
